### ISSUE TITLE
Panic when configuring cluster

### ISSUE THREAD

**Issue by aguerra** [luizalabs/teresa-cli#47]
Uname: 

```
Darwin heaven.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
```

Probably related to the configuration file `~/.teresa/config.yaml`:

```
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x4d0940, 0xc4202bd6d0)
    /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/luizalabs/teresa-cli/cmd.setCluster(0x7fff5fbffab2, 0xa, 0x7fff5fbffac0, 0x24, 0x557000, 0xc4202d1950, 0x21, 0xb, 0xc4204c3bb8)
    /Users/xxxx/projects/go/src/github.com/luizalabs/teresa-cli/cmd/cluster_config.go:69 +0x1c1
github.com/luizalabs/teresa-cli/cmd.glob..func8(0x817540, 0xc4202d18c0, 0x1, 0x3)
Users/xxxx/projects/go/src/github.com/luizalabs/teresa-cli/cmd/cluster_config.go:28 +0xa4
github.com/luizalabs/teresa-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x817540, 0xc4202d1830, 0x3, 0x3, 0x817540, 0xc4202d1830)
...
```

**Comment by danielgerep-luizalabs** [comment]
@aguerra acabei de instalar e tive o mesmo problema, executei como `sudo` e passou mas não sei se é correto usar `sudo`

**Comment by danielgerep-luizalabs** [comment]
@aguerra Has a (temporary) workaround

Edit the config file (`~/.teresa/config.yaml`) with:

```version: 0.1.2
clusters:
  staging:
    server: https://your-server-dns
```

**Comment by drgarcia1986** [comment]
@danielgerep-luizalabs I'm trying to reproduce this issue
